[package]
name = "pasm"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[workspace]
members = ["src-tauri"]

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
magic-crypt = "3.1.6"
